
urls = [
        "https://hh.ru/search/vacancy?text=fastapi+junior&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=python+junior&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=backend+junior&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=python&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=backend&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=fastapi&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=стажировка+backend&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=стажировка+python&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=стажировка+fastapi&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=backend+стажер&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=python+стажер&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=fastapi+стажер&area=113&experience=between1And3&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=fastapi+junior&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=python+junior&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=backend+junior&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=python&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=backend&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=fastapi&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=стажировка+backend&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=стажировка+python&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=стажировка+fastapi&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=backend+стажер&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=python+стажер&area=113&experience=noExperience&order_by=publication_time",
        "https://hh.ru/search/vacancy?text=fastapi+стажер&area=113&experience=noExperience&order_by=publication_time",
]